name: Release CLI binaries

on:
  push:

jobs:
  build-native-binary:
    strategy:
      matrix:
        fail-fast: false
        os: [ubuntu-latest, macos-latest, windows-latest]
        gu-binary: [gu, gu.cmd]
        executable-path: [./target/code-with-quarkus-1.0.0-SNAPSHOT-runner, .\target\code-with-quarkus-1.0.0-SNAPSHOT-runner.exe]
        exclude:
          - os: ubuntu-latest
            gu-binary: gu.cmd
            executable-path: .\target\code-with-quarkus-1.0.0-SNAPSHOT-runner.exe
          - os: macos-latest
            gu-binary: gu.cmd
            executable-path: .\target\code-with-quarkus-1.0.0-SNAPSHOT-runner.exe
          - os: windows-latest
            gu-binary: gu
            executable-path: ./target/code-with-quarkus-1.0.0-SNAPSHOT-runner
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: '22.1.0'
          java: 'java11'
      - name: Install native-image component
        run: |
          ${{ matrix.gu-binary }} install native-image
      - name: Compile to native binaries
        run: |
          ./mvnw package -Pnative
      - name: 'Upload executable'
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: code-with-quarkus-${{ matrix.os }}
          path: ${{ matrix.executable-path }}
